[project]
name = "nixconf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "click>=8.2.1",
  "hyprpy>=0.2.0"
]

[tool.ty.environment]
python = ".venv"
